 export const dummyArticles = [
    { id: 1, username: 'john_doe', content: 'This is the content of Article 1.This is the content of Article 1.This is the content of Article 1.', category: 'Corporate', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg' },
    { id: 2, username: 'Article 2', content: 'This is the content of Article 2.', category: 'Health', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png' },
    { id: 3, username: 'Article 3', content: 'This is the content of Article 3.', category: 'Government', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg' },
    { id: 4, username: 'Article 4', content: 'This is the content of Article 4.', category: 'Business', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 5, username: 'Article 5', content: 'This is the content of Article 5.', category: 'Opinion', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg'},
    { id: 6, username: 'Article 6', content: 'This is the content of Article 6.', category: 'Food', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 7, username: 'Article 7', content: 'This is the content of Article 7.', category: 'Lifestyle', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg'},
    { id: 8, username: 'Article 8', content: 'This is the content of Article 8.', category: 'Charity', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 9, username: 'Article 9', content: 'This is the content of Article 9.', category: 'Sports', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg'},
    { id: 10, username: 'Article 10', content: 'This is the content of Article 10.', category: 'SME', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 11, username: 'Article 11', content: 'This is the content of Article 11.', category: 'Politics', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg'},
    { id: 12, username: 'Article 12', content: 'This is the content of Article 12.', category: 'Property', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 13, username: 'Article 13', content: 'This is the content of Article 13.', category: 'News', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg'},
    { id: 14, username: 'Article 14', content: 'This is the content of Article 14.', category: 'Investment', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 15, username: 'Article 15', content: 'This is the content of Article 15.', category: 'Education', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg'},
    { id: 16, username: 'Article 16', content: 'This is the content of Article 16.', category: 'Automotive', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 17, username: 'Article 17', content: 'This is the content of Article 17.', category: 'Technology', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg'},
    { id: 18, username: 'Article 18', content: 'This is the content of Article 18.', category: 'Agriculture', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 19, username: 'Article 19', content: 'This is the content of Article 19.', category: 'Entertainment',timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg'},
    { id: 20, username: 'Article 20', content: 'This is the content of Article 20.', category: 'Travel', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 21, username: 'Article 21', content: 'This is the content of Article 21.', category: 'Corporate', timestamp: new Date().toString(), status: 'Draft', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 22, username: 'Article 22', content: 'This is the content of Article 22.', category: 'Health', timestamp: new Date().toString(), status: 'Draft', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 23, username: 'Article 23', content: 'This is the content of Article 23.', category: 'Government', timestamp: new Date().toString(), status: 'Draft', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg'},
    { id: 24, username: 'Article 24', content: 'This is the content of Article 24.', category: 'Business', timestamp: new Date().toString(), status: 'Draft', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png'},
    { id: 25, username: 'Article 25', content: 'This is the content of Article 25.', category: 'Opinion', timestamp: new Date().toString(), status: 'Draft', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg'},
    { id: 26, username: 'lwk1334', content: 'This is the content of Article 26.This is the content of Article 26.This is the content of Article 26.', category: 'Corporate', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/cardmaterial1@3x.png' },
 { id: 27, username: 'James', content: 'This is the content of Article 27.This is the content of Article 27.This is the content of Article 27.', category: 'Corporate', timestamp: new Date().toString(), status: 'Published', imagePath: 'https://imbrgdnynoeyqyotpxaq.supabase.co/storage/v1/object/public/testing/pexels-flickr-145994.jpg' },

    // Add more articles with their respective data
  ];

  export default dummyArticles;
  
  
  